#!/bin/bash

# for local, change http://pareto.uab.es/mcreel to file:///home/michael/Mystuff -> econometrics_local.lyx
# for Pelican, change http://pareto.uab.es/mcreel to file:///home/user -> econometrics_pelican.lyx

cp econometrics.lyx econometrics_local.lyx
sed -i 's@http://pareto.uab.es/mcreel@file:///home/michael/Mystuff@g' econometrics_local.lyx


# make pdfs
lyx -e pdf2 econometrics.lyx
lyx -e pdf2 econometrics_local.lyx

