#!/bin/bash
cp econometrics.lyx econometrics_local.lyx
cp econometrics.lyx econometrics_pelican.lyx
sync

#/usr/bin/perl -i -p0e "s#https://github.com/mcreel/Econometrics/blob/master#file:///home/michael/Mystuff/Econometrics#g" econometrics_local.lyx
#/usr/bin/perl -i -p0e "s#https://github.com/mcreel/Econometrics/blob/master#file:///home/user/Econometrics#g" econometrics_pelican.lyx

# for local, replace
# https://github.com/mcreel/Econometrics/blob/master
# with
# file:///home/michael/Mystuff/Econometrics

# for live CD, replace
# https://github.com/mcreel/Econometrics/blob/master
# with
# file:///home/user/Econometrics

# then do
# lyx -e pdf2 econometrics.lyx
# lyx -e pdf2 econometrics_local.lyx
# lyx -e pdf2 econometrics_pelican.lyx

# get rid of extra versions
#rm econometrics_local.lyx
#rm econometrics_pelican.lyx


