#!/bin/bash

# for local, change http://pareto.uab.es/mcreel to file:///home/michael/Mystuff -> econometrics_local.lyx
# for Pelican, change http://pareto.uab.es/mcreel to file:///home/user -> econometrics_pelican.lyx

cp econometrics.lyx econometrics_local.lyx
sed -i 's@https://github.com/mcreel/Econometrics/blob/master/@file:///home/michael/Mystuff/Econometrics/@g' econometrics_local.lyx

cp econometrics.lyx econometrics_pelican.lyx
sed -i 's@http://pareto.uab.es/mcreel@file:///home/user@g' econometrics_pelican.lyx

# make pdfs
lyx -e pdf2 econometrics.lyx
lyx -e pdf2 econometrics_local.lyx
lyx -e pdf2 econometrics_pelican.lyx

# get rid of extra versions
rm econometrics_local.lyx
rm econometrics_pelican.lyx

#--------------------------------------------------
# Zip it up
cd ../
rm -f ./Econometrics.tgz
rm -f ./Econometrics.zip
tar cfz Econometrics.tgz ./Econometrics
zip -r Econometrics.zip ./Econometrics
#
cd Econometrics
#--------------------------------------------------
