#!/bin/bash
for i in {1..24}
do
	cp TEMPLATEMODFILE.mod SimpleModel"$i".mod
	sync
	sed -i "s/parameterfile1/parameterfile$i/"g SimpleModel"$i".mod
	sed -i "s/state1/state$i/g" SimpleModel"$i".mod

done

	 
