% example showing how to do likelihood ratio test
% for data generated by CLRM with normality
%
% this is the same as NormalExample.m, but with the LR test at the bottom
%
% run this a number of times to check size
%
% change H0 to make it false to check power. Also, play with sample size.


% sample size
n = 100;

% random true parameters
theta = [1;-1;0;1];
b = theta(1:3,:);
sig = theta(4,:);

% generate random data
x = [ones(n,1) rand(n,2)];
e = sig*randn(n,1);
y = x*b + e;

% do ML: note minus sign, also, examine NormalLF to see what's done
[thetahat, logL] = fminunc(@(theta) -NormalLF(theta, y, x), theta);
logL = -logL; % convert from minimization
% results
fprintf('the true parameters\n');
theta
fprintf('the ML estimates\n');
thetahat
fprintf('the unrestricted average log-likelihood\n');
logL


% test that second coefficient equal to some value
R = [0 1 0 0];
r = 0;
[thetahat_r, logL_r] = sqp(thetahat, @(theta) -NormalLF(theta, y, x), @(theta) R*theta-r, [], [], []); %Octave replacement for fmincon
logL_r = -logL_r; % convert from minimization
% results
fprintf('the restricted ML estimates\n');
thetahat_r
fprintf('the restricted average log-likelihood\n');
logL_r
fprintf('the LR test\n');
LR = 2*n*(logL-logL_r);
LR
fprintf('p-value of the LR test\n');
1-chi2cdf(LR,1)







