% example showing how to do maximum likelihood estimation
% for data generated by CLRM with normality

% sample size
n = 100;

% random true parameters
theta = [1;-1;0;1];
b = theta(1:3,:);
sig = theta(4,:);

% generate random data
x = [ones(n,1) rand(n,2)];
e = sig*randn(n,1);
y = x*b + e;

% do ML: note minus sign, also, examine NormalLF to see what's done
thetahat = fminunc(@(theta) -NormalLF(theta, y, x), theta);

% results
fprintf('the true parameters\n');
theta

fprintf('the ML estimates\n');
thetahat

